name: gauge-test-sample-in-github-actions

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# テスト結果レポートをGitHub Pagesに公開するために必要
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# テスト結果レポートをGitHub Pagesに公開するために必要
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Test Job
  execute-gauge-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install Python Libraries
        run: |
          python --version
          poetry --version
          pip list
          poetry install
          pip list

      - name: Setup & Verify Gauge
        run: |
          which curl
          curl --version
          curl -SsL https://downloads.gauge.org/stable | sh
          gauge install python --version 0.3.17
          gauge version

      - name: Run Test
        run: |
          gauge run specs

      # このレポート保存処理はzipにかためてworkflow結果に貼るだけ
      # GitHub Pagesへの公開もやっているので不要ならコメントアウトしても良い
      - name: Save Report
        uses: actions/upload-artifact@v3
        with:
          name: gauge-test-report
          path: reports/html-report

      # 以降はテスト結果レポートをGitHub Pagesにデプロイするための準備

      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./reports/html-report
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  # Deployment Report Job
  deploy-report:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: execute-gauge-test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
